DROP TABLE IF EXISTS alert_states;
DROP TABLE IF EXISTS check_results;
DROP TABLE IF EXISTS checks;
DROP TABLE IF EXISTS services;

ALTER TABLE nodes DROP COLUMN IF EXISTS capabilities;
ALTER TABLE nodes DROP COLUMN IF EXISTS ssh_password_enc;
ALTER TABLE nodes DROP COLUMN IF EXISTS ssh_auth_method;
ALTER TABLE nodes DROP COLUMN IF EXISTS ssh_enabled;
ALTER TABLE nodes DROP COLUMN IF EXISTS is_enabled;
ALTER TABLE nodes DROP COLUMN IF EXISTS provider;
ALTER TABLE nodes DROP COLUMN IF EXISTS region;
ALTER TABLE nodes DROP COLUMN IF EXISTS host;
