package httpapi

import (
	"time"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/prometheus/client_golang/prometheus/promhttp"

	"agr_3x_ui/internal/http/middleware"
)

func NewRouter(h *Handler) *gin.Engine {
	r := gin.New()
	r.Use(gin.Recovery())
	r.Use(gin.Logger())
	r.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"http://localhost:5173"},
		AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Authorization", "X-Requested-With"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	}))
	r.GET("/metrics", gin.WrapH(promhttp.Handler()))

	api := r.Group("/api")
	api.POST("/auth/login", h.Login)
	api.POST("/auth/refresh", h.Refresh)
	api.POST("/auth/logout", h.Logout)
	api.POST("/signup", h.Signup)
	api.POST("/auth/2fa/recovery", h.SendRecoveryCode)
	api.POST("/auth/webauthn/login/options", h.WebAuthnLoginOptions)
	api.POST("/auth/webauthn/login/verify", h.WebAuthnLoginVerify)
	api.GET("/nodes/:id/ssh", h.SSHWebsocket)
	api.POST("/telegram/webhook", h.TelegramWebhook)
	api.GET("/healthz", h.Healthz)
	api.GET("/settings/public", h.GetPublicSettings)
	api.GET("/dashboard/stream", h.DashboardStream)
	api.GET("/agent/ping", h.AgentPing)
	api.POST("/agent/register", h.AgentRegister)
	api.POST("/agent/heartbeat", h.AgentAuth(), h.AgentHeartbeat)
	api.GET("/ops/jobs/:id/public", h.GetOpsJobPublic)
	api.GET("/ops/jobs/:id", h.OpsReadAuth(), h.GetOpsJob)
	api.GET("/ops/jobs/:id/items", h.OpsReadAuth(), h.GetOpsJobItems)

	auth := api.Group("")
	auth.Use(middleware.JWTAuth(h.JWTSecret))

	readRoles := []string{middleware.RoleAdmin, middleware.RoleOperator, middleware.RoleViewer}
	writeRoles := []string{middleware.RoleAdmin, middleware.RoleOperator}

	auth.GET("/orgs", middleware.RequireRoles(readRoles...), h.ListOrgs)
	auth.POST("/orgs", middleware.RequireRoles(writeRoles...), h.CreateOrg)
	orgsRead := auth.Group("/orgs/:orgId", middleware.RequireOrgRole(h.DB, "viewer"))
	orgsWrite := auth.Group("/orgs/:orgId", middleware.RequireOrgRole(h.DB, "admin"))
	orgsRead.GET("/nodes", h.ListOrgNodes)
	orgsRead.GET("/nodes/:nodeId", h.GetOrgNode)
	orgsRead.GET("/invites", h.OrgListInvites)
	orgsRead.GET("/users", h.ListOrgUsers)
	orgsRead.GET("/keys", h.ListOrgKeys)
	orgsRead.GET("/keys/:keyId/download", h.DownloadOrgKey)
	orgsRead.GET("/observability/prom/settings", h.GetPromObservabilitySettings)
	orgsRead.GET("/observability/prom/targets", h.ListPromObservabilityTargets)
	orgsWrite.GET("/export", h.ExportOrgConfig)
	orgsWrite.POST("/nodes", h.CreateOrgNode)
	orgsWrite.DELETE("/nodes/:nodeId", h.DeleteOrgNode)
	orgsWrite.POST("/nodes/:nodeId/agent/revoke", h.RevokeAgent)
	orgsWrite.POST("/users", h.CreateOrgUser)
	orgsWrite.PATCH("/users/:userId", h.UpdateOrgUser)
	orgsWrite.DELETE("/users/:userId", h.DeleteOrgUser)
	orgsWrite.POST("/keys", h.UploadOrgKey)
	orgsWrite.PATCH("/keys/:keyId", h.UpdateOrgKey)
	orgsWrite.DELETE("/keys/:keyId", h.DeleteOrgKey)
	orgsWrite.POST("/invites", h.OrgCreateInvite)
	orgsWrite.POST("/invites/:id/revoke", h.OrgRevokeInvite)
	orgsWrite.POST("/import", h.ImportOrgConfig)
	orgsWrite.PUT("/observability/prom/settings", h.UpdatePromObservabilitySettings)
	orgsWrite.POST("/observability/prom/targets", h.CreatePromObservabilityTarget)
	orgsWrite.PATCH("/observability/prom/targets/:targetId", h.UpdatePromObservabilityTarget)
	orgsWrite.DELETE("/observability/prom/targets/:targetId", h.DeletePromObservabilityTarget)
	orgsWrite.POST("/observability/prom/targets/test", h.TestPromObservabilityTarget)
	orgsWrite.POST("/observability/prom/reload", h.ReloadPromObservability)
	orgsWrite.GET("/observability/prom/sd", h.GetPromObservabilitySD)

	auth.GET("/nodes", middleware.RequireRoles(readRoles...), h.ListNodes)
	auth.GET("/nodes/:id", middleware.RequireRoles(readRoles...), h.GetNode)
	auth.GET("/nodes/:id/diagnostics", middleware.RequireRoles(readRoles...), h.GetNodeDiagnostics)
	auth.GET("/nodes/:id/status", middleware.RequireRoles(readRoles...), h.GetNodeStatus)
	auth.GET("/nodes/:id/uptime", middleware.RequireRoles(readRoles...), h.GetNodeUptime)
	auth.GET("/nodes/:id/metrics", middleware.RequireRoles(readRoles...), h.GetNodeMetrics)
	auth.GET("/nodes/:id/files/roots", middleware.RequireRoles(readRoles...), h.ListFileRoots)
	auth.GET("/nodes/:id/files/list", middleware.RequireRoles(readRoles...), h.ListFiles)
	auth.GET("/nodes/:id/files/read", middleware.RequireRoles(readRoles...), h.ReadFileChunk)
	auth.GET("/nodes/:id/files/tail", middleware.RequireRoles(readRoles...), h.TailFile)
	auth.GET("/nodes/:id/files/download", middleware.RequireRoles(readRoles...), h.DownloadFile)
	auth.POST("/nodes/:id/files/upload", middleware.RequireRoles(writeRoles...), h.UploadFile)
	auth.POST("/nodes/:id/files/mkdir", middleware.RequireRoles(writeRoles...), h.Mkdir)
	auth.POST("/nodes/:id/files/rename", middleware.RequireRoles(writeRoles...), h.RenamePath)
	auth.POST("/nodes/:id/files/delete", middleware.RequireRoles(writeRoles...), h.DeletePath)
	auth.GET("/nodes/:id/fs/list", middleware.RequireRoles(middleware.RoleAdmin, middleware.RoleOperator), h.FSList)
	auth.GET("/nodes/:id/fs/stat", middleware.RequireRoles(middleware.RoleAdmin, middleware.RoleOperator), h.FSStat)
	auth.GET("/nodes/:id/fs/read", middleware.RequireRoles(middleware.RoleAdmin, middleware.RoleOperator), h.FSRead)
	auth.GET("/nodes/:id/fs/download", middleware.RequireRoles(middleware.RoleAdmin, middleware.RoleOperator), h.FSDownload)
	auth.PUT("/nodes/:id/fs/write", middleware.RequireRoles(middleware.RoleAdmin), h.FSWrite)
	auth.POST("/nodes/:id/fs/mkdir", middleware.RequireRoles(middleware.RoleAdmin), h.FSMkdir)
	auth.POST("/nodes/:id/fs/rename", middleware.RequireRoles(middleware.RoleAdmin), h.FSRename)
	auth.POST("/nodes/:id/fs/delete", middleware.RequireRoles(middleware.RoleAdmin), h.FSDelete)
	auth.POST("/nodes/:id/fs/upload", middleware.RequireRoles(middleware.RoleAdmin), h.FSUpload)
	dbAuth := api.Group("")
	dbAuth.Use(middleware.JWTAuthWithQuery(h.JWTSecret, "token"))
	dbAuth.GET("/nodes/:id/db/sqlite/list", middleware.RequireRoles(middleware.RoleAdmin), h.ListNodeSqlite)
	dbAuth.POST("/nodes/:id/db/sqlite/start", middleware.RequireRoles(middleware.RoleAdmin), h.StartNodeSqlite)
	dbAuth.POST("/nodes/:id/db/adminer/start", middleware.RequireRoles(middleware.RoleAdmin), h.StartNodeAdminer)
	dbAuth.Any("/nodes/:id/db/sqlite/ui/*path", middleware.RequireRoles(middleware.RoleAdmin), h.ProxyNodeSqlite)
	dbAuth.Any("/nodes/:id/db/adminer/ui/*path", middleware.RequireRoles(middleware.RoleAdmin), h.ProxyNodeAdminer)

	auth.GET("/nodes/:id/services", middleware.RequireRoles(readRoles...), h.ListServices)
	auth.POST("/nodes/:id/services", middleware.RequireRoles(writeRoles...), h.CreateService)
	auth.GET("/nodes/:id/bots", middleware.RequireRoles(readRoles...), h.ListBots)
	auth.POST("/nodes/:id/bots", middleware.RequireRoles(writeRoles...), h.CreateBot)
	auth.GET("/services", middleware.RequireRoles(readRoles...), h.ListAllServices)
	auth.POST("/services", middleware.RequireRoles(writeRoles...), h.CreateServiceGlobal)
	auth.PATCH("/nodes/:id/services/:serviceId", middleware.RequireRoles(writeRoles...), h.UpdateService)
	auth.DELETE("/nodes/:id/services/:serviceId", middleware.RequireRoles(writeRoles...), h.DeleteService)
	auth.PUT("/services/:service_id", middleware.RequireRoles(writeRoles...), h.UpdateService)
	auth.DELETE("/services/:service_id", middleware.RequireRoles(writeRoles...), h.DeleteService)
	auth.POST("/services/:service_id/run", middleware.RequireRoles(writeRoles...), h.RunServiceCheck)
	auth.GET("/services/:service_id/results", middleware.RequireRoles(readRoles...), h.ListServiceResults)
	auth.GET("/bots/:bot_id", middleware.RequireRoles(readRoles...), h.GetBot)
	auth.PUT("/bots/:bot_id", middleware.RequireRoles(writeRoles...), h.UpdateBot)
	auth.DELETE("/bots/:bot_id", middleware.RequireRoles(writeRoles...), h.DeleteBot)
	auth.POST("/bots/:bot_id/run-now", middleware.RequireRoles(writeRoles...), h.RunBotCheck)
	auth.GET("/bots/:bot_id/results", middleware.RequireRoles(readRoles...), h.ListBotResults)

	auth.GET("/nodes/:id/checks", middleware.RequireRoles(readRoles...), h.ListNodeChecks)
	auth.POST("/nodes/:id/checks", middleware.RequireRoles(writeRoles...), h.CreateNodeCheck)
	auth.GET("/services/:service_id/checks", middleware.RequireRoles(readRoles...), h.ListServiceChecks)
	auth.POST("/services/:service_id/checks", middleware.RequireRoles(writeRoles...), h.CreateServiceCheck)
	auth.PATCH("/checks/:id", middleware.RequireRoles(writeRoles...), h.UpdateCheck)
	auth.DELETE("/checks/:id", middleware.RequireRoles(writeRoles...), h.DeleteCheck)
	auth.GET("/checks/:id/results", middleware.RequireRoles(readRoles...), h.ListCheckResults)

	auth.POST("/nodes", middleware.RequireRoles(writeRoles...), h.CreateNode)
	auth.PATCH("/nodes/:id", middleware.RequireRoles(writeRoles...), h.UpdateNode)
	auth.POST("/nodes/:id/test", middleware.RequireRoles(writeRoles...), h.TestNode)
	auth.POST("/validate/node", middleware.RequireRoles(writeRoles...), h.ValidateNode)
	auth.POST("/utils/convert-ssh-key", middleware.RequireRoles(writeRoles...), h.ConvertSSHKey)

	auth.DELETE("/nodes/:id", middleware.RequireRoles(middleware.RoleAdmin), h.DeleteNode)

	auth.POST("/nodes/:id/actions/reboot", middleware.RequireRoles(writeRoles...), h.RebootServer)
	auth.POST("/nodes/:id/actions/:action/plan", middleware.RequireRoles(writeRoles...), h.PlanNodeAction)
	auth.POST("/nodes/:id/actions/:action/run", middleware.RequireRoles(writeRoles...), h.RunNodeAction)

	auth.GET("/audit", middleware.RequireRoles(middleware.RoleAdmin), h.ListAuditLogs)
	auth.GET("/alerts", middleware.RequireRoles(readRoles...), h.ListAlerts)
	auth.GET("/incidents", middleware.RequireRoles(readRoles...), h.ListIncidents)
	auth.POST("/incidents/:id/ack", middleware.RequireRoles(writeRoles...), h.AckIncident)
	auth.GET("/telegram/settings", middleware.RequireRoles(middleware.RoleAdmin), h.GetTelegramSettings)
	auth.PUT("/telegram/settings", middleware.RequireRoles(middleware.RoleAdmin), h.UpdateTelegramSettings)
	auth.POST("/telegram/test", middleware.RequireRoles(middleware.RoleAdmin), h.SendTelegramTest)
	auth.GET("/prometheus/settings", middleware.RequireRoles(middleware.RoleAdmin), h.GetPrometheusSettings)
	auth.PUT("/prometheus/settings", middleware.RequireRoles(middleware.RoleAdmin), h.UpdatePrometheusSettings)
	auth.POST("/prometheus/test", middleware.RequireRoles(middleware.RoleAdmin), h.TestPrometheusConnection)
	auth.POST("/prometheus/query", middleware.RequireRoles(readRoles...), h.QueryPrometheus)
	auth.POST("/alerts/:fingerprint/mute", middleware.RequireRoles(writeRoles...), h.MuteAlert)
	auth.POST("/alerts/:fingerprint/retry", middleware.RequireRoles(writeRoles...), h.RetryAlert)

	auth.POST("/ops/jobs", middleware.RequireRoles(writeRoles...), h.CreateOpsJob)
	auth.POST("/ops/deploy-agent", middleware.RequireRoles(writeRoles...), h.CreateDeployAgent)
	auth.POST("/tasks/bulk", middleware.RequireRoles(writeRoles...), h.CreateTaskBulk)
	auth.GET("/ops/jobs/:id/stream", middleware.RequireRoles(readRoles...), h.OpsJobStream)
	auth.GET("/tasks/:id", middleware.RequireRoles(readRoles...), h.GetTask)
	auth.GET("/tasks/:id/items", middleware.RequireRoles(readRoles...), h.GetTaskItems)
	auth.GET("/settings/agent-deploy-defaults", middleware.RequireRoles(readRoles...), h.GetAgentDeployDefaults)
	auth.GET("/dashboard/summary", middleware.RequireRoles(readRoles...), h.GetDashboardSummary)
	auth.GET("/dashboard/active-users", middleware.RequireRoles(readRoles...), h.GetDashboardActiveUsers)
	auth.GET("/system/status", middleware.RequireRoles(readRoles...), h.GetSystemStatus)

	auth.GET("/users", middleware.RequireRoles(middleware.RoleAdmin), h.ListUsers)
	auth.POST("/users", middleware.RequireRoles(middleware.RoleAdmin), h.CreateUser)
	auth.PATCH("/users/:id", middleware.RequireRoles(middleware.RoleAdmin), h.UpdateUser)
	auth.DELETE("/users/:id", middleware.RequireRoles(middleware.RoleAdmin), h.DeleteUser)
	auth.POST("/admin/invites", middleware.RequireRoles(middleware.RoleAdmin), h.AdminCreateInvite)
	auth.GET("/admin/invites", middleware.RequireRoles(middleware.RoleAdmin), h.AdminListInvites)
	auth.POST("/admin/invites/:id/revoke", middleware.RequireRoles(middleware.RoleAdmin), h.AdminRevokeInvite)

	auth.GET("/auth/2fa/status", middleware.RequireRoles(readRoles...), h.GetTOTPStatus)
	auth.POST("/auth/2fa/setup", middleware.RequireRoles(writeRoles...), h.SetupTOTP)
	auth.POST("/auth/2fa/verify", middleware.RequireRoles(writeRoles...), h.VerifyTOTP)
	auth.POST("/auth/2fa/disable", middleware.RequireRoles(writeRoles...), h.DisableTOTP)
	auth.POST("/auth/webauthn/register/options", middleware.RequireRoles(writeRoles...), h.WebAuthnRegisterOptions)
	auth.POST("/auth/webauthn/register/verify", middleware.RequireRoles(writeRoles...), h.WebAuthnRegisterVerify)
	auth.GET("/auth/webauthn/credentials", middleware.RequireRoles(readRoles...), h.ListWebAuthnCredentials)
	auth.DELETE("/auth/webauthn/credentials/:id", middleware.RequireRoles(writeRoles...), h.DeleteWebAuthnCredential)

	return r
}
